#!/usr/bin/env bash

function main {
  set -x

  if [[ "$#" -gt 0 ]]; then
    exec "$@"
  else
    install -d -m 0700 /home/ubuntu/.ssh
    if [[ -f /data/authorized_keys ]]; then
      install -m 0600 /data/authorized_keys /home/ubuntu/.ssh/authorized_keys
    fi
    curl -s https://github.com/defn.keys >> /home/ubuntu/.ssh/authorized_keys

    exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o UsePrivilegeSeparation=sandbox
  fi
}

main "$@"
