pipeline:
  rebase:
    image: imma/ubuntu:base
    commands:
      - cd /home/ubuntu && sudo -H -u ubuntu ./docker/rebase/bootstrap
      - cd /home/ubuntu && sudo -H -u ubuntu ./exec/home block stale
