clone:
  git:
    image: ubuntu
    commands: true

pipeline:
  rebase:
    image: imma/ubuntu:base
    commands:
      - cd /home/ubuntu && sudo -H -u ubuntu cp .gitconfig.template-https .gitconfig
      - cd /home/ubuntu && sudo -H -u ubuntu cp .ssh/config.template .ssh/config
      - cd /home/ubuntu && sudo -H -u ubuntu git fetch
      - cd /home/ubuntu && sudo -H -u ubuntu git checkout -f "${CI_COMMIT_BRANCH}"
      - cd /home/ubuntu && sudo -H -u ubuntu git reset --hard "${CI_COMMIT_SHA}"
      - cd /home/ubuntu && sudo -H -u ubuntu ./docker/rebase/bootstrap
      - cd /home/ubuntu && sudo -H -u ubuntu ./exec/home block stale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA}:/data
