---
driver:
  name: vagrant
  ssh:
    insert_key: false
  synced_folders:
    - [ "/data", "/data" ]
    - [ ".", "/tmp/home" ]
  box_check_update: false

transport:
  forward_agent: true
  username: ubuntu

provisioner:
  name: shell
  require_chef_omnibus: false

verifier:
  name: inspec
  inspec_tests:
    - test/smoke/default

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true
      image: ubuntu:xenial
  - name: centos-7.4
    driver:
      linked_clone: true
      image: centos:7.4.1708
  - name: amazonlinux
    driver_config:
      linked_clone: true
      image: amazonlinux:2017.09
      platform: rhel

suites:
  - name: virtualbox
    provisioner:
      script: bootstrap-vagrant.sh
    driver:
      provider: virtualbox
  - name: vmware
    provisioner:
      script: bootstrap-vagrant.sh
    driver:
      provider: vmware_fusion
  - name: parallels
    provisioner:
      script: bootstrap-vagrant.sh
    driver:
      provider: parallels
  - name: aws
    provisioner:
      script: bootstrap-aws.sh
    driver:
      name: ec2
      image_id: ami-1d4e7a66
      interface: private_dns
      aws_ssh_key_id: terraform-0061b86515b826cf28edd6f5c8
      security_group_ids: [ sg-135b7c6c, sg-df587fa0, sg-aa5d5ed5 ]
      subnet_id: subnet-e6a849bc
      associate_public_ip: true
      iam_profile_name: adm-admin-build
  - name: docker
    provisioner:
      script: bootstrap-docker.sh
    driver:
      name: docker
      require_chef_omnibus: false
      use_sudo: false
      use_cache: false
      build_context: false
      volume:
        - /data:/data
        - /config:/config
      username: ubuntu
