---
driver:
  name: vagrant
  ssh:
    insert_key: false
  synced_folders:
    - [ "/data", "/data" ]
    - [ ".", "/tmp/home" ]
  box_check_update: false

transport:
  forward_agent: true
  username: ubuntu

provisioner:
  name: shell
  require_chef_omnibus: false

verifier:
  name: inspec
  inspec_tests:
    - test/smoke/default

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true
      image: ubuntu:xenial
  - name: centos-7.4
    driver:
      linked_clone: true
      image: centos:7.4.1708
  - name: amazonlinux
    driver_config:
      linked_clone: true
      image: amazonlinux:2017.09
      platform: rhel

suites:
  - name: virtualbox
    provisioner:
      script: bootstrap-vagrant.sh
    driver:
      provider: virtualbox
    excludes:
      - amazonlinux
  - name: vmware
    provisioner:
      script: bootstrap-vagrant.sh
    driver:
      provider: vmware_fusion
    excludes:
      - amazonlinux
  - name: parallels
    provisioner:
      script: bootstrap-vagrant.sh
    driver:
      provider: parallels
    excludes:
      - amazonlinux
  - name: aws
    provisioner:
      script: bootstrap-aws.sh
    driver:
      name: ec2
      interface: private_dns
      associate_public_ip: true
      image_id: <% ENV['FOGG_AMI'] %>
      aws_ssh_key_id: <% ENV['FOGG_KEY_PAIR'] %>
      security_group_ids: <% (ENV['FOGG_SG']||"").split("") %>
      subnet_id: <% ENV['FOGG_SUBNET'] %>
      iam_profile_name: <% ENV['FOGG_IAM_PROFILE'] %>
  - name: docker
    provisioner:
      script: bootstrap-docker.sh
    driver:
      name: docker
      require_chef_omnibus: false
      use_sudo: false
      use_cache: false
      build_context: false
      volume:
        - /data:/data
      username: ubuntu
