---
driver:
  name: vagrant
  ssh:
    insert_key: false
  synced_folders:
    - [ "/data", "/data", "type: :nfs" ]
    - [ ".", "/tmp/home", "type: :nfs" ]
  box_check_update: false

transport:
  forward_agent: true
  username: ubuntu

provisioner:
  name: shell

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true

suites:
  - name: virtualbox
    driver:
      provider: virtualbox
      network:
        - [ "private_network", { ip: "172.28.128.11" } ]
    provisioner:
      script: bootstrap-vagrant.sh
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: vmware
    driver:
      provider: vmware_fusion
    provisioner:
      script: bootstrap-vagrant.sh
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: aws
    driver:
      name: ec2
      image_id: ami-1d4e7a66
      interface: private_dns
      aws_ssh_key_id: terraform-0061b86515b826cf28edd6f5c8
      security_group_ids: [ sg-135b7c6c, sg-df587fa0, sg-aa5d5ed5 ]
      subnet_id: subnet-e6a849bc
      associate_public_ip: true
      iam_profile_name: adm-admin-build
    provisioner:
      script: bootstrap-aws.sh
  - name: docker
    driver:
      name: docker
      image:  ubuntu:xenial
      require_chef_omnibus: false
      volume:
        - /data:/data
        - /config:/data
    provisioner:
      script: bootstrap-docker.sh
