---
driver:
  name: vagrant
  synced_folders:
    - ["/data", "/data", "type: :nfs"]
    - [".", "/tmp/home", "type: :nfs"]

transport:
  forward_agent: true

provisioner:
  name: shell

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
