---
driver:
  name: vagrant
  ssh:
    insert_key: false
  synced_folders:
    - [ "/data", "/data", "type: :nfs" ]
    - [ ".", "/tmp/home", "type: :nfs" ]
  box_check_update: false

transport:
  forward_agent: true

provisioner:
  name: shell

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true

suites:
  - name: virtualbox
    driver:
      provider: virtualbox
      network:
        - [ "private_network", { ip: "172.28.128.11" } ]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: vmware
    driver:
      provider: vmware_fusion
      network:
        - [ "private_network", { ip: "172.28.129.11" } ]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
