---
driver:
  name: vagrant
  ssh:
    insert_key: false
  synced_folders:
    - [ "/data", "/data" ]
    - [ ".", "/tmp/home" ]
  box_check_update: false

transport:
  forward_agent: true
  username: ubuntu

provisioner:
  name: shell
  require_chef_omnibus: false

verifier:
  name: inspec
  inspec_tests:
    - test/smoke/default

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true
      image: ubuntu:xenial
  - name: centos-7.4
    driver:
      linked_clone: true
      image: centos:7.4.1708
  - name: amazonlinux
    driver_config:
      linked_clone: true
      image: amazonlinux:2017.09
      platform: rhel

suites:
  - name: localhost
    provisioner:
      script: bootstrap-localhost.sh
    driver:
      name: ssh
      hostname: localhost
      port: 22
      username: ubuntu
    excludes: [ centos-7.4, amazonlinux]
  - name: virtualbox
    provisioner:
      script: bootstrap.sh
    driver:
      provider: virtualbox
    excludes:
      - amazonlinux
  - name: vmware
    provisioner:
      script: bootstrap.sh
    driver:
      provider: vmware_fusion
    excludes:
      - amazonlinux
  - name: parallels
    provisioner:
      script: bootstrap.sh
    driver:
      provider: parallels
    excludes:
      - amazonlinux
  - name: aws
    provisioner:
      script: bootstrap.sh
    driver:
      name: ec2
      interface: private_dns
      instance_type: <%= ENV['FOGG_INSTANCE_TYPE'] || 't2.nano' %>
      associate_public_ip: true
      aws_ssh_key_id: <%= ENV['FOGG_SVC_SSH_KEY'] %>
      security_group_ids: 
        - <%= ENV['FOGG_ENV_SG'] %>
        - <%= ENV['FOGG_APP_SG'] %>
        - <%= ENV['FOGG_SVC_SG'] %>
      subnet_id: <%= (ENV['FOGG_SVC_SUBNETS']||"").split(/\s+/)[0] %>
      iam_profile_name: <%= ENV['FOGG_SVC_IAM_PROFILE'] %>
      user_data: "#!/bin/bash\nmkdir -p /data\napt-get install -y nfs-common\nmount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 efs.<%= ENV['FOGG_ENV'] %>.immanent.io:/ /data\n"
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 20
            delete_on_termination: true
  - name: docker
    provisioner:
      script: bootstrap.sh
    driver:
      name: docker
      require_chef_omnibus: false
      use_sudo: false
      use_cache: false
      build_context: false
      volume:
        - /data:/data
      username: ubuntu
