languageCode = "en-us"
title = "Hasta Nunca!"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
relativeURLS = true
contentDir = ".content"
publishDir = ".public"

[params]
# General information
author = "defn"
description = "Hasta Nunca!"
copyright = "Apache License, Version 2.0"

# Repository
provider = "GitHub"
repo_url = "https://github.com/imma/ubuntu"

version = "0.9.0"
logo = "images/logo.png"
favicon = ""

permalink = "#"

# Custom assets
custom_css = []
custom_js  = []

# Syntax highlighting theme
highlight_css  = ""

[params.palette]
primary = "teal"
accent  = "blue"

[params.font]
text = "Ubuntu"
code = "Ubuntu Mono"

[blackfriday]
smartypants	= true
fractions = true
smartDashes = true
plainIDAnchors = true

[[menu.main]]
name   = ""
url    = "/"
weight = 10
