version: '3.2'

services:
  shell:
    build: devshell
    image: imma/devshell
    privileged: true
    ports:
      - "22"
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true
      - .:/src
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/work:/tmp/work

volumes:
  data:
    external: true
