version: "3"

services:
  shell:
    build: b
    privileged: true
    ports:
      - "22"
      - "9500"
    volumes:
      - ${DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.m2:/home/ubuntu/.m2
