version: '3.2'

services:
  shell:
    build: b
    network_mode: bridge
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - ${DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
