version: '3.2'

services:
  shell:
    build: devshell
    image: imma/devshell
    privileged: true
    ports:
      - "22"
    volumes:
      - .:/src
      - ${DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/work:/tmp/work
