version: '3.2'

services:
  shell:
    build: devshell
		image: imma/devshell
    privileged: true
    ports:
      - "22"
    volumes:
      - .:/src
      - ${DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/work:/tmp/work
    volumes_from:
      - cache_artifacts
      - cache_keys
      - cargo
      - etc
    network_mode: bridge
  cache_artifacts:
    image: tianon/true
    command: /true
    volumes:
      - /hab/cache/artifacts
  cache_keys:
    image: tianon/true
    command: /true
    volumes:
      - /hab/cache/keys
  cargo:
    image: tianon/true
    command: /true
    volumes:
      - /cargo-cache
  etc:
    image: tianon/true
    command: /true
    volumes:
      - /hab/etc
