#!/usr/bin/env bash

function main {
  if type -P yum; then
    sudo yum install -y gnupg2 gnupg2-smime tmux irssi jq unzip || true
  elif type -P apt-get; then
    sudo apt-get update || true
    sudo apt-get install -y libpcsclite1 pcscd pcsc-tools tmux irssi jq unzip g++ python || true
  fi

  mv ubuntu/.git .
  rm -rf ubuntu
  git reset --hard
  script/setup
  make cache
}

main "$@"
