#!/usr/bin/env bash

function main {
  case "$(id -u -n)" in
    root)
      if type -P yum; then
        yum install -y git sudo || true
      elif type -P apt-get; then
        apt-get update || true
        apt-get install -y git sudo || true
      fi

      sudo -H -u ubuntu "$0"
      ;;
    ubuntu)
      cd
      git clone https://github.com/imma/ubuntu
      ubuntu/setup
      source .bash_profile
      block bootstrap
      ;;
  esac
}

main "$@"
