#!/usr/bin/env bash

function main {
  mv ubuntu/.git .
  rm -rf ubuntu
  git reset --hard
  script/setup
  make cache
  cp .gitconfig.template .gitconfig
  sudo yum update
  sudo yum install -y gnupg2 gnupg2-smime tmux irssi
  exec bash
}

main "$@"
