#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  git pull
  git submodule update --init --recursive || true
}

source sub "$BASH_SOURCE" "$@"
