#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  cd "$shome"
  git grep "cache.nih" | egrep '^(.gemrc|.npmrc|.pip|.pydistutils.cfg)' | cut -d: -f1 | sort -u | runmany 'perl -pe "m{cache.nih} && s{^}{#}" -i "$1"'
}

source sub "$BASH_SOURCE" "$@"
