#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  git grep "cache.nih" | egrep '^(.gemrc|.npmrc|.pip|.pydistutils.cfg|.bundle/config)' | cut -d: -f1 | sort -u | runmany 'git checkout -- "$1"'
}

source sub "$BASH_SOURCE" "$@"
