#!/usr/bin/env bash

function main {
  cd

  git fetch
	git reset --hard
  git pull
  cp .gitconfig.template-https .gitconfig

  script/setup
  script/bootstrap
  make cache

  for a in {1..5}; do git clean -ffd || true; done
  sudo rm -f ~root/.ssh/authorized_keys
  (set +f; rm -f .ssh/authorized_keys .ssh/*id_rsa*)
  rm -rf "$WRKOBJDIR"
  rm -rf "$PKGSRCDIR"
  sudo apt-get clean
} 

main "$@"
