#!/usr/bin/env bash

function prep {
  git fetch
}

function main {
  set -x

  prep

  if [[ -n "${CI_COMMIT_SHA}" ]]; then
    git checkout -f "${CI_COMMIT_BRANCH}"
    git reset --hard "${CI_COMMIT_SHA}"
  else
    git reset --hard
    git pull
  fi

	mkdir -p .ssh
	if ssh -o Include=meh 2>&1 | grep -q 'Bad'; then
		cat .ssh/config.template
	else
		perl -pe 's{^#Include}{Include}' .ssh/config.template
	fi > .ssh/config
	chmod 600 .ssh/config

	mkdir -p .gnupg
	chmod 0700 .gnupg
	touch .gnupg/gpg.conf
	chmod 0600 .gnupg/gpg.conf

	git submodule update --init
	make cache

  script/bootstrap
  make cache

  for a in {1..5}; do git clean -ffd || true; done
  sudo rm -f ~root/.ssh/authorized_keys
  (set +f; rm -f .ssh/authorized_keys .ssh/*id_rsa*)
  rm -rf "$WRKOBJDIR"
  rm -rf "$PKGSRCDIR"
  sudo apt-get clean
} 

main "$@"
