version: '3.2'

services:
  rebase:
    image: imma/ubuntu:rebase1
    privileged: true
    ports:
      - "22"
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true

volumes:
  data:
    external: true
