#!/usr/bin/env bash

function prep {
  ssh -o StrictHostKeyChecking=no github.com true 2>/dev/null || true

  git clone git@github.com:imma/ubuntu
  mv ubuntu/.git .
  rm -rf ubuntu
}

function user_data {
  sudo apt-get update
  sudo apt-get install -y \
    openssh-server curl lsb-release sudo make locales python build-essential \
    aptitude rsync jq netcat software-properties-common \
    python-software-properties net-tools dnsmasq unzip perl ruby language-pack-en \
    vim man screen runit nfs-common portmap gettext-base libffi-dev libssl-dev \
    libreadline-dev zlib1g-dev libxml2-dev libxslt1-dev autoconf automake libtool

  sudo add-apt-repository -y ppa:git-core/ppa
  sudo apt-get update
  sudo apt-get install -y git

  sudo locale-gen en_US.UTF-8
  sudo dpkg-reconfigure --frontend=noninteractive locales
  sudo update-locale LANG=en_US.UTF-8

  sudo groupadd -g 497 docker
  usermod -G docker ubuntu

  install -d -m 0700 -o ubuntu -g ubuntu /data
}

function main {
  user_data

  prep

  git reset --hard
  git pull

  script/setup
  make cache
  source .bash_profile

  for a in {1..5}; do git clean -ffd || true; done
  sudo rm -f ~root/.ssh/authorized_keys
  (set +f; rm -f .ssh/authorized_keys .ssh/*id_rsa*)
  rm -rf "$WRKOBJDIR"
  rm -rf "$PKGSRCDIR"
  sudo apt-get clean
} 

main "$@"


