#!/usr/bin/env bash

function main {
  set -x

  ssh -o StrictHostKeyChecking=no github.com true 2>/dev/null || true

  git clone git@github.com:imma/ubuntu
  mv ubuntu/.git .
  rm -rf ubuntu

  git reset --hard
  git pull

  script/setup
  make cache
  source .bash_profile

  for a in {1..5}; do git clean -ffd || true; done
  sudo rm -f ~root/.ssh/authorized_keys
  (set +f; rm -f .ssh/authorized_keys .ssh/*id_rsa*)
  rm -rf "$WRKOBJDIR"
  rm -rf "$PKGSRCDIR"
  sudo apt-get clean
} 

main "$@"
