#!/usr/bin/env bash

function main {
  set -exfu

  ssh -o StrictHostKeyChecking=no github.com true 2>/dev/null || true

  cd

  if [[ -f .bash_profile ]]; then
    source .bash_profile
  fi

  if [[ ! -d .git ]]; then
    git clone https://github.com/imma/ubuntu
    mv ubuntu/.git .
    rm -rf ubuntu

    git reset --hard
  fi

  cp .gitconfig.template-https .gitconfig

  if [[ ! -f .bashrc.cache ]]; then
    script/setup
    make cache
  fi

  source .bash_profile
  block sync
  source .bash_profile

  mkdir -p .ssh
  if ssh -o Include=meh 2>&1 | grep -q 'Bad'; then
    cat .ssh/config.template
  else
    perl -pe 's{^#Include}{Include}' .ssh/config.template
  fi > .ssh/config
  chmod 600 .ssh/config

  mkdir -p .gnupg
  chmod 0700 .gnupg
  touch .gnupg/gpg.conf
  chmod 0600 .gnupg/gpg.conf

  sudo ln -nfs home /Users

  set +x
  sudo aptitude update
  make cache
  source .bash_profile
  set -x

  for a in {1..5}; do git clean -ffd || true; done
  rm -rf "$WRKOBJDIR"
  rm -rf "$PKGSRCDIR"
  sudo apt-get clean
  if type -P yarn >/dev/null; then
    yarn cache clean
  fi

  if [[ -n "${1:-}" ]]; then
    touch "$1"
  fi
} 

main "$@"
