#!/usr/bin/env bash

function main {
  set -x

  if [[ "$#" -gt 0 ]]; then
    exec "$@"
  else
    install -d -m 0700 /home/ubuntu/.ssh
    if [[ -f /data/authorized_keys ]]; then
      install -m 0600 /data/authorized_keys /home/ubuntu/.ssh/authorized_keys
    else
      curl -s https://github.com/defn.keys
    fi > /home/ubuntu/.ssh/authorized_keys

    local pth_done="${SERVICE_DONE:-/etc/hosts}"
    if [[ ! -f "$pth_done" ]]; then
      /bootstrap "$pth_done"
    else
      /bootstrap "$pth_done"
      sudo mkdir -p /var/run/sshd
      exec sudo /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o UsePrivilegeSeparation=sandbox
    fi
  fi
}

main "$@"
