name 'defn'
maintainer 'defn ghiem'
maintainer_email 'iam@defn.sh'
license 'All Rights Reserved'
description 'Installs/Configures defn'
long_description 'Installs/Configures defn'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/defn/defn/issues'
source_url 'https://github.com/defn/defn'
supports 'ubuntu'
