#!/usr/bin/env bash

function main {
  set -x

  cd

  ssh -o StrictHostKeyChecking=no github.com uname -a || true

  git clone git@github.com:imma/ubuntu
  mv ubuntu/.git .
  git reset --hard
  git clean -ffd

  script/setup
  script/bootstrap
} 

main "$@"
