#!/usr/bin/env bash

function main {
  set -x

  cd

  ssh -o StrictHostKeyChecking=no github.com uname -a || true

  if [[ ! -e .git ]]; then
    git clone git@github.com:imma/ubuntu
    mv ubuntu/.git .
    git reset --hard
    git clean -ffd
  fi

  git fetch
  git pull

  script/setup
  script/bootstrap
} 

main "$@"
