---
- name: Get the fogg hostname
  command: fogg hostname
  register: fogg_hostname
  when: (hostname is not defined) and (ansible_virtualization_type == "xen")
- name: Set hostname fact using fogg
  set_fact:
    hostname: "{{ fogg_hostname.stdout }}"
  when: fogg_hostname.stdout is defined
- name: Add /etc/hosts entry
  lineinfile: >
    dest=/etc/hosts 
    regexp="^127\.0\.1\.1" 
    state=present 
    line="127.0.1.1 {{hostname}}"
  become: yes
  when: hostname is defined and hostname != ""

- name: Set /etc/hostname
  template: >
    src=hostname.j2
    dest=/etc/hostname
    owner=root
    group=root
    mode=0644
  become: yes
  when: hostname is defined and hostname != ""

- name: Get hostname
  command: uname -n
  register: get_hostname
  when: hostname is defined and hostname != ""

- name: Rename host
  command: hostname {{ hostname }}
  become: yes
  when: hostname is defined and hostname != "" and get_hostname.stdout != hostname

- name: Reset Blockfile.lock
  command: chdir="{{ansible_env.HOME}}" git checkout Blockfile.lock

- name: Get ssh-agent status
  command: ssh-add -l
  register: ssh_agent
  ignore_errors: yes
