version: '2'

services:
  dnsproxy:
    image: imma/ubuntu:argo
    restart: always
    networks:
      default:
        ipv4_address: 192.168.201.2
  dnsmasq:
    image: imma/ubuntu:dnsmasq
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      default:
        ipv4_address: 192.168.201.3
  openvpn:
    image: imma/ubuntu:openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - ./config/openvpn:/etc/openvpn
    networks:
      default:
        ipv4_address: 192.168.201.4

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24
          gateway: 192.168.201.1
