#!/usr/bin/env bash

function ubuntu_home_bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  sudo usermod -a -G docker ubuntu || true
  sudo usermod -a -G staff ubuntu || true
}

ubuntu_home_bootstrap "$@"
