#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure sysutils/cdrtools
  pkg ensure sysutils/findutils
  pkg ensure security/openssh
}

main "$@"
