#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure sysutils/cdrtools
  pkg ensure sysutils/findutils
  pkg ensure sysutils/coreutils
  
  block compile virtualenv
  (set +f; cd "$shome/bin" && ln -nfs ../vendor/virtualenv/bin/powerline* "$shome/bin/")
}

main "$@"
