#!/usr/bin/env bash

function setup_submodules {
  if ! git submodule update --init --remote --no-fetch -j 10; then
    git submodule update --init
  fi
  git submodule foreach git checkout master
}

function setup_block {
  if [[ ! -e "$shome/work/block/.git" ]]; then
    (cd "$shome/work" && git clone git@github.com:imma/block)
  else
    (cd "$shome/work/block" && git pull)
  fi
  "$shome/work/block/script/cibuild"
  source "$shome/work/block/script/profile"
}

function build_blocks {
  cd "$shome"
  require
  home update
  "$shome/work/block/script/cibuild" ~
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  #setup_submodules
  setup_block
  build_blocks
  make cache
}

main "$@"
