#!/usr/bin/env bash

function setup_ssh {
  mkdir -p "$shome/work"

  mkdir -p ~/.ssh
  cat <<EOF | tee -a ~/.ssh/config
Host github.com
  StrictHostKeyChecking no
  ForwardAgent no
EOF
}

function setup_submodules {
  git submodule update --init
  git submodule foreach git checkout master
}

function setup_base {
  pushd "$shome/work/base"
  script/bootstrap
  popd
}

function setup_block {
  if [[ ! -d "$shome/work/block/.git" ]]; then
    (cd "$shome/work" && git clone git@github.com:imma/block)
  fi
  "$shome/work/block/script/cibuild"
  source "$shome/work/block/script/profile"
}

function setup_cache {
  if [[ ! -d "$shome/work/cache/.git" ]]; then
    (cd "$shome/work" && git clone git@github.com:imma/cache)
  fi
  "$shome/work/block/script/cibuild" "$shome/work/cache"
  pushd "$shome/work/cache" >/dev/null
  require
  popd >/dev/null
}

function build_blocks {
  cd ~
  require
  "$shome/work/block/script/cibuild" ~
}

function cleanup {
  pushd ~
  git checkout .ssh/config
  popd
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  setup_ssh
  setup_submodules
  setup_base
  setup_block
  setup_cache
  build_blocks
  require
  cleanup
}

main "$@"
