#!/usr/bin/env bash

function main {
	if systemctl; then
		if [[ -d /var/lib/cloud/instance/. ]]; then
			while true; do
				if [[ -f "/var/lib/cloud/instance/boot-finished" ]]; then 
					break
				fi
				echo "Waiting for cloud-init boot-finished: $(date)"
				sleep 3
			done
		fi
	fi

  ssh -o StrictHostKeyChecking=no github.com 2>/dev/null || true
}

main "$@"
