#!/usr/bin/env bash

function main {
	while true; do
		if [[ -f "/var/lib/cloud/instance/boot-finished" ]]; then break; fi
    echo "Waiting for cloud-init boot-finished: $(date)"
		sleep 3
	done

  set -x

  git pull
  git reset --hard

  block clone
  block runmany 'cd $1 && git checkout master'
  home update

  script/update
  script/update 172.28.128.1

  sudo apt install -y dnsmasq
  { echo 'server=/consul/127.0.0.1#5354'
    echo 'server=127.0.0.1#5354'
    echo 'address=/nih/172.28.128.1'
  } | sudo tee /etc/dnsmasq.d/nih
  sudo systemctl restart dnsmasq

  { echo 'DOCKER_OPTS="--dns 172.28.128.1"'
  } | sudo tee /etc/default/docker
  sudo systemctl restart docker
}

main "$@"
