#!/usr/bin/env bash

function main {
  if systemctl 1>/dev/null 2>&1; then
    if [[ -d /var/lib/cloud/instance/. ]]; then
      while true; do
        if [[ -f "/var/lib/cloud/instance/boot-finished" ]]; then 
          break
        fi
        echo "Waiting for cloud-init boot-finished: $(date)"
        sleep 3
      done
    fi
  fi
}

main "$@"
