#!/usr/bin/env bash

function main {
  set -x

  script/cibuild

  runmany 'git clone git@github.com:imma/$1 work/$1 || true' admin nexus gogs
  runmany 'cd $1 && make download' ~ ~/work/{admin,nexus,gogs}

  sudo apt install -y dnsmasq
  { echo 'server=/consul/127.0.0.1#5354'
    echo 'server=127.0.0.1#5354'
    echo 'address=/nih/172.28.128.1'
  } | sudo tee /etc/dnsmasq.d/nih

  { echo 'DOCKER_OPTS="--dns 172.28.128.1"'
  } | sudo tee /etc/default/docker
}

main "$@"
