#!/usr/bin/env bash

function main {
	while true; do
		if [[ -f "/var/lib/cloud/instance/boot-finished" ]]; then break; fi
    echo "Waiting for cloud-init boot-finished: $(date)"
		sleep 3
	done

  git reset --hard
  home update
  block bootstrap
  make cache
  script/update
}

main "$@"
