#!/usr/bin/env bash

shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
source "$shome/script/profile"

function host {
  if ! test -d /config/.git; then
    sudo install -d -o ubuntu -g ubuntu /data
    sudo install -d -o ubuntu -g ubuntu /data/cache
    sudo install -d -o ubuntu -g ubuntu /config
    git clone -b "$(cd "$shome" && git rev-parse --abbrev-ref HEAD)" git@github.com:imma/imma-config /config
  fi

  sudo dpkg --configure -a
  sudo apt-get update
  sudo apt-get install -y gettext-base

  chmod 700 ~/.gnupg

  (cd /config & git pull)
  git submodule update --init
  make cache
  source .bashrc
  make sync

  "$shome/work/block/script/cibuild"
  block bootstrap

  sync
}

function container {
  eval $(aws ecr get-login)

  local image="$(docker images | grep "$(aws ecr describe-repositories | jq -r --arg repo block '.repositories | map(select(.repositoryName == $repo))[].repositoryUri')" | awk '$2 == "ubuntu" { print $3 }')"

  if [[ -z "$image" ]]; then
    return
  fi

  make reset-docker-ubuntu
  script/configure
  make docker
  make clean
  make prune

  sync
}

function main {
  set -exfu

  if ! "$@" test -d .git; then
    "$@" -A ssh -o StrictHostKeyChecking=no git@github.com true 2>/dev/null || true

    "$@" -A git clone -b "$(cd "$shome" && git rev-parse --abbrev-ref HEAD)" "$(git config --get remote.origin.url)"
    "$@" mv ubuntu/.git .
    "$@" rm -rf ubuntu
    "$@" git reset --hard
    "$@" chmod 0640 .ssh/config
  fi
  
  "$@" -A git pull
  "$@" -A script/deploy host
  if [[ "$(facts | jq -r '.virtualization_type')" != "docker" ]]; then
    "$@" -A script/deploy container
  fi
}

set -exfu
umask 0022
case "${1:-}" in
  host)
    shift
    host "$@"
    ;;
  container)
    shift
    container"$@"
    ;;
  *)
    main "$@"
    ;;
esac
