#!/usr/bin/env bash

shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
source "$shome/script/profile"

function host {
  sudo dpkg --configure -a
  sudo apt-get update
  sudo apt-get install -y make python build-essential aptitude

  chmod 700 ~/.gnupg

  git submodule update --init
  make cache
  set +x; source .bashrc; set -x;
  make sync

  "$shome/work/block/script/cibuild"
  block bootstrap
  make lock
  rm -rf work/admin

  sync
}

function container {
  runmany docker pull $(aws ecr describe-repositories | jq -r --arg repo block '.repositories | map(select(.repositoryName == $repo))[].repositoryUri'):'$1'  -- base ubuntu "$@"
  make reset-docker-ubuntu
  script/configure
  make clean
  make prune

  sync
}

function main {
  set -exfu

  local nm_branch="$(cd "$shome" && git rev-parse --abbrev-ref HEAD)"
  local url_origin="$(git config --get remote.origin.url)"

  if ! "$@" test -d .git; then
    "$@" -A ssh -o StrictHostKeyChecking=no git@github.com true 2>/dev/null || true

    "$@" -A git clone -b "${nm_branch}" "${url_origin}"
    "$@" mv ubuntu/.git .
    "$@" rm -rf ubuntu
    "$@" git reset --hard
    "$@" chmod 0640 .ssh/config
  else
    "$@" git remote remove origin || true
    "$@" git remote add origin "${url_origin}"
    "$@" rsync -ia .gitconfig.template .gitconfig
    "$@" -A git fetch
    "$@" git reset --hard "origin/${nm_branch}"
    "$@" chmod 0640 .ssh/config
    "$@" -A git checkout "${nm_branch}"
    "$@" -A git branch --set-upstream-to "origin/$nm_branch"
  fi
  
  "$@" -A script/deploy host
}

set -exfu
umask 0022
case "${1:-}" in
  host)
    shift
    host "$@"
    ;;
  container)
    shift
    container "$@"
    ;;
  *)
    main "$@"
    ;;
esac
