#!/usr/bin/env bash

shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
source "$shome/script/profile"

function remote {
  set -exfu

  if ! test -d /config/.git; then
    sudo install -d -o ubuntu -g ubuntu /data
    sudo install -d -o ubuntu -g ubuntu /data/cache
    sudo install -d -o ubuntu -g ubuntu /config
    git clone -b "$(cd "$shome" && git rev-parse --abbrev-ref HEAD)" git@github.com:imma/imma-config /config
  fi

  if curl -s --max-time 30 http://cache.nih | grep Nexus; then
    home enable cache 2>/dev/null || true
  fi

  sudo aptitude install -y gettext-base

  git pull
  git submodule update --init
  make cache
  source .bashrc
  make sync

  script/cibuild

  home disable cache
}

function main {
  set -exfu

  if ! "$@" test -d .git; then
    "$@" -A ssh -o StrictHostKeyChecking=no git@github.com true 2>/dev/null || true

    "$@" -A git clone -b "$(cd "$shome" && git rev-parse --abbrev-ref HEAD)" git@github.com:imma/ubuntu
    "$@" mv ubuntu/.git .
    "$@" rm -rf ubuntu
    "$@" git reset --hard
    "$@" chmod 0640 .ssh/config
  fi

  "$@" -A script/deploy remote

}

umask 0022
if [[ "${1:-}" == "remote" ]]; then
  shift
  remote "$@"
else
  main "$@"
fi
