#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if ! type -P mkisofs >/dev/null; then
    return 1
  fi

  if ! type -P gxargs >/dev/null; then
    return 1
  fi

  if ! type -P gdate >/dev/null; then
    return 1
  fi

  if ! type -P powerline >/dev/null; then
    return 1
  fi

  return 0
}

main "$@"
