#!/usr/bin/env bash

function _ubuntu_home_profile {
  local shome="${_ubuntu_home_home:="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$PATH:$shome/bin:$shome/exec"
  export ANSIBLE_ROLES_PATH="$shome/roles${ANSIBLE_ROLES_PATH:+:${ANSIBLE_ROLES_PATH}}"

  export LC_ALL=en_US.UTF-8  
  export LANG=en_US.UTF-8
}

_ubuntu_home_profile
