#!/usr/bin/env bash

function _ubuntu_home_profile {
  local shome="${_ubuntu_home_home:="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  export ANSIBLE_ROLES_PATH="$shome/roles${ANSIBLE_ROLES_PATH:+:${ANSIBLE_ROLES_PATH}}"

  if [[ ! -f "$HOME/.aws/credentials" ]]; then
    if [[ -f "/config/aws/credentials" ]]; then
      export AWS_SHARED_CREDENTIALS_FILE="/config/aws/credentials"
    fi
  fi

	case "$(uname -s)" in
		Darwin)
			export LC_ALL=en_US.UTF-8  
			export LANG=en_US.UTF-8
			;;
	esac
}

_ubuntu_home_profile
