#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  source "$shome/.bashrc"

  case "${1:-}" in
    screen)
      shift
      while ! screen -S runit -X status; do
        screen -S runit -d -m "$shome/script/server" "$@"
        sleep 1
        echo "detaching..." 1>&2
      done
      ;;
    default)
      sudo '/etc/rc.local'
      exec "$BLOCK_PATH/runit/script/server" "$@"
      ;;
    docker)
      sudo rm -f /var/lib/cloud/instance
      sudo cloud-init init
      sudo cloud-init modules
      sudo cloud-init modules -m final
      exec "$shome/script/server"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

main "$@"

