#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  umask 0022
  source "$shome/.bashrc"

  for nm_service in "$@"; do
    case "$nm_service" in
      screen)
        shift
        while ! screen -S runit -X status; do
          screen -S runit -d -m "$shome/script/server" "$@"
          sleep 1
          echo "detaching..." 1>&2
        done
        ;;
      default)
        if [[ -f ~/etc/rc.local ]]; then
          ~/etc/rc.local
        fi
        exec "$BLOCK_PATH/runit/script/server" "$@"
        ;;
      *)
        block compile service "$nm_service"
        ;;
    esac
  done
}

main "$@"

