#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      sudo rm -f /etc/dnsmasq.d/nih
      sudo rm -f /etc/default/docker
      sudo systemctl restart dnsmasq
      sudo systemctl restart docker
      ;;
  esac

  rm -f /config/ssh/authorized_keys
}

main "$@"
