#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local vip="${1:-172.28.29.250}"

  if ifconfig vboxnet0 2>/dev/null; then
    VBoxManage hostonlyif ipconfig vboxnet0 --ip 172.28.128.1
  fi

  case "$(uname -s)" in
    Darwin)
      sudo ifconfig lo0 alias "$vip" netmask 255.255.255.0
      brew install dnsmasq
      brew services restart dnsmasq
      ;;
    Linux)
      sudo ifconfig lo:0 "$vip" netmask 255.255.255.0 up
      sudo systemctl restart dnsmasq
      ;;
  esac
}

main "$@"
