#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local vip="${1:-172.28.29.250}"

  case "$(uname -s)" in
    Darwin)
      sudo ifconfig lo0 alias "$vip" netmask 255.255.255.0
      ;;
    Linux)
      sudo ifconfig lo:0 "$vip" up
      ;;
  esac
}

main "$@"
