#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      sudo ifconfig lo0 alias 172.28.29.250
      ;;
    Linux)
      sudo ifconfig lo:0 172.28.29.250 up
      ;;
  esac
}

main "$@"
